### ISSUE TITLE
Error reading constraint over relationship

### ISSUE THREAD

**Issue by masmangan** [ocularium/ocularium#75]
From W & K, R & L:

firstLine:[context ocularium::examples::royalloyal::LoyaltyProgram::levels]
elementSplit:[[, ocularium::examples::royalloyal::LoyaltyProgram::levels]]
elementName:[ocularium::examples::royalloyal::LoyaltyProgram::levels]
qualifiedName:[[ocularium, examples, royalloyal, LoyaltyProgram, levels]]
java.lang.ArrayIndexOutOfBoundsException: 0
	at ocularium.internal.OculariumFacade.importOCL0(OculariumFacade.java:266)
	at ocularium.internal.OculariumFacade.importOCL(OculariumFacade.java:225)
	at ocularium.actions.ImportOCLAction.run(ImportOCLAction.java:66)
	at com.change_vision.astah.extension.plugin.ui.PluginAction.actionPerformed(X:95)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)

**Comment by masmangan** [comment]
Export gets constraints and its elements.
Import get elements then add constraints.
levels is exported but not imported.

Operations and attributes are being found during import.

**Comment by masmangan** [comment]
Is { ordered } an OCL constraint? Is it an UML constraint?

**Comment by masmangan** [comment]
If we do not export ordered, we don't need to import it.
